In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt  
from sklearn.datasets import make_blobs
import plotly
import plotly.graph_objs as go

In [2]:
def create_nn_model(x, y, l):
    input_layer = x
    weights1 = np.random.uniform(-1, 1, (input_layer.shape[1], 4))
    
    weights2 = np.random.uniform(-1, 1, (4, 1))
    label = y
    output_layer = np.zeros(y.shape)
    learning_rate = l
    
    return {'input_layer': input_layer, 'weights1': weights1, 'weights2': weights2, 'label': label, 'output_layer': output_layer, 'learning_rate': learning_rate}

In [3]:
x, y = make_blobs(n_samples=10, centers=2, n_features=3)

y = np.expand_dims(y, axis=1)
x.shape, y.shape

((10, 3), (10, 1))

In [4]:
learning_rate = 0.1

model = create_nn_model(x, y, learning_rate)

In [5]:
model['input_layer'].shape

(10, 3)

In [6]:
model['input_layer']

array([[ 5.54814281, -1.51450266,  8.558644  ],
       [ 7.12279685, -0.668284  ,  9.38931493],
       [-5.04342613, -0.27484999, -6.23688144],
       [ 5.411357  , -0.34101995,  8.15913109],
       [ 6.83908217, -2.65496536,  6.95943256],
       [-5.88572205, -0.45473389, -6.75765872],
       [-6.86242932, -0.33713297, -8.02965261],
       [-4.4260451 ,  0.05682522, -7.90837899],
       [-6.32299774, -2.69505995, -5.33118162],
       [ 5.81164929, -1.96459213,  8.77658496]])

In [7]:
model['weights1'].shape

(3, 4)

In [8]:
model['weights1']

array([[-0.33220646, -0.59250386, -0.38102847, -0.33109529],
       [-0.20794196, -0.09595286,  0.65213365,  0.15493682],
       [ 0.68703055, -0.18593218, -0.96530758,  0.71930204]])

In [9]:
model['weights2'].shape

(4, 1)

In [10]:
model['weights2']

array([[-0.00271053],
       [-0.80223561],
       [ 0.49178362],
       [-0.54258082]])

In [11]:
model['label'].shape

(10, 1)

In [12]:
model['output_layer'].shape

(10, 1)

In [13]:
model['output_layer'] #ŷ

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [14]:
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

In [15]:
def loss(model):
    return sum((model['label'] - model['output_layer'])**2)

In [16]:
def feedforward(model):
    model['layer1'] = sigmoid(np.dot(model['input_layer'], model['weights1']))
    model['output_layer'] = sigmoid(np.dot(model['layer1'], model['weights2']))               

In [17]:
def backprop(model):
    d_weights2 = np.dot(model['layer1'].T, (2*(model['label']- model['output_layer']) * sigmoid_derivative(model['output_layer'])))
    d_weights1 = np.dot(model['input_layer'].T,  (np.dot(2*(model['label'] - model['output_layer']) * sigmoid_derivative(model['output_layer']), model['weights2'].T) * sigmoid_derivative(model['layer1'])))
    
    model['weights2'] += model['learning_rate']*d_weights2
    model['weights1'] += model['learning_rate']*d_weights1

# **Train Model**

In [18]:
history=[]
epoch = 500

for i in range(epoch):
    feedforward(model)
    backprop(model)
    history.append(loss(model))

In [19]:
df = pd.DataFrame(history, columns=['loss'])
df.head()

loss
0  2.862143
1  2.292443
2  1.826204
3  1.467495
4  1.201951

In [20]:
h1 = go.Scatter(y=df['loss'], 
                    mode="lines", line=dict(
                    width=2,
                    color='blue'),
                    name="loss")

data = [h1]

layout1 = go.Layout(title='Loss',
                   xaxis=dict(title='Epochs'),
                   yaxis=dict(title=''))
fig1 = go.Figure(data, layout=layout1)
plotly.offline.iplot(fig1)